"""Adding missing enums name, and types

Revision ID: 18ab2315b71a
Revises: 9d71f050bfa3
Create Date: 2026-02-22 17:13:39.300649

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18ab2315b71a"
down_revision: Union[str, Sequence[str], None] = "9d71f050bfa3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE invoicestatus RENAME TO invoice_status")
    op.execute("ALTER TYPE paymentmethod RENAME TO payment_method")
    op.alter_column(
        "invoices",
        "status",
        existing_type=postgresql.ENUM(
            "PAID", "UNPAID", "PARTIAL", name="invoicestatus"
        ),
        type_=sa.Enum("PAID", "UNPAID", "PARTIAL", name="invoice_status"),
        existing_nullable=False,
    )
    op.alter_column(
        "payments",
        "method",
        existing_type=postgresql.ENUM("FAWRY", "VISA", name="paymentmethod"),
        type_=sa.Enum("FAWRY", "VISA", name="payment_method"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE invoice_status RENAME TO invoicestatus")
    op.execute("ALTER TYPE payment_method RENAME TO paymentmethod")
    op.alter_column(
        "payments",
        "method",
        existing_type=sa.Enum("FAWRY", "VISA", name="payment_method"),
        type_=postgresql.ENUM("FAWRY", "VISA", name="paymentmethod"),
        existing_nullable=False,
    )
    op.alter_column(
        "invoices",
        "status",
        existing_type=sa.Enum("PAID", "UNPAID", "PARTIAL", name="invoice_status"),
        type_=postgresql.ENUM("PAID", "UNPAID", "PARTIAL", name="invoicestatus"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
