"""Adding Grading, and Finance.

Revision ID: 78712b21adff
Revises: d97b651f8b86
Create Date: 2026-02-22 17:03:37.774309

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78712b21adff"
down_revision: Union[str, Sequence[str], None] = "d97b651f8b86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grade_distributions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("offering_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("max_score", sa.DECIMAL(), nullable=False),
        sa.Column("weight", sa.DECIMAL(), nullable=False),
        sa.ForeignKeyConstraint(
            ["offering_id"],
            ["course_offerings.id"],
            name=op.f("fk_grade_distributions_offering_id_course_offerings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grade_distributions")),
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("semester_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.DECIMAL(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PAID", "UNPAID", "PARTIAL", name="invoicestatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["semester_id"],
            ["semesters.id"],
            name=op.f("fk_invoices_semester_id_semesters"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.user_id"],
            name=op.f("fk_invoices_student_id_students"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("invoice_id", sa.BigInteger(), nullable=False),
        sa.Column("amount", sa.DECIMAL(), nullable=False),
        sa.Column(
            "method", sa.Enum("FAWRY", "VISA", name="paymentmethod"), nullable=False
        ),
        sa.Column("reference_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_payments_invoice_id_invoices"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_table(
        "student_scores",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("enrollment_id", sa.BigInteger(), nullable=False),
        sa.Column("distribution_id", sa.BigInteger(), nullable=False),
        sa.Column("score", sa.DECIMAL(), nullable=False),
        sa.Column("grader_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["distribution_id"],
            ["grade_distributions.id"],
            name=op.f("fk_student_scores_distribution_id_grade_distributions"),
        ),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["enrollments.id"],
            name=op.f("fk_student_scores_enrollment_id_enrollments"),
        ),
        sa.ForeignKeyConstraint(
            ["grader_id"], ["users.id"], name=op.f("fk_student_scores_grader_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_scores")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student_scores")
    op.drop_table("payments")
    op.drop_table("invoices")
    op.drop_table("grade_distributions")
    # ### end Alembic commands ###
