"""Adding essential SQLAlchehecmy relationships

Revision ID: 8895b2fb86fb
Revises: 18ab2315b71a
Create Date: 2026-02-22 18:13:24.789740

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8895b2fb86fb"
down_revision: Union[str, Sequence[str], None] = "18ab2315b71a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roles", sa.Column("name_ar", sa.String(length=50), nullable=False))
    op.add_column("roles", sa.Column("name_en", sa.String(length=50), nullable=False))
    op.drop_constraint(op.f("uq_roles_name"), "roles", type_="unique")
    op.create_unique_constraint(op.f("uq_roles_name_ar"), "roles", ["name_ar"])
    op.create_unique_constraint(op.f("uq_roles_name_en"), "roles", ["name_en"])
    op.drop_column("roles", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roles",
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.drop_constraint(op.f("uq_roles_name_en"), "roles", type_="unique")
    op.drop_constraint(op.f("uq_roles_name_ar"), "roles", type_="unique")
    op.create_unique_constraint(
        op.f("uq_roles_name"), "roles", ["name"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("roles", "name_en")
    op.drop_column("roles", "name_ar")
    # ### end Alembic commands ###
