"""Re-Adding Grading, and Finance.

Revision ID: 9d71f050bfa3
Revises: 78712b21adff
Create Date: 2026-02-22 17:05:29.616841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d71f050bfa3'
down_revision: Union[str, Sequence[str], None] = '78712b21adff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
