"""Initial commit

Revision ID: d97b651f8b86
Revises:
Create Date: 2026-02-22 16:49:30.865235

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d97b651f8b86"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name_ar", sa.String(length=100), nullable=False),
        sa.Column("name_en", sa.String(length=100), nullable=False),
        sa.Column("credit_hours", sa.Integer(), nullable=False),
        sa.Column("lecture_hours", sa.Integer(), nullable=False),
        sa.Column("lab_hours", sa.Integer(), nullable=False),
        sa.Column("tutorial_hours", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
        sa.UniqueConstraint("code", name=op.f("uq_courses_code")),
    )
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_ar", sa.String(length=100), nullable=False),
        sa.Column("name_en", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
        sa.UniqueConstraint("code", name=op.f("uq_departments_code")),
    )
    op.create_table(
        "faculty_bylaws",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("issue_year", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_faculty_bylaws")),
        sa.UniqueConstraint("name", name=op.f("uq_faculty_bylaws_name")),
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_ar", sa.String(length=255), nullable=False),
        sa.Column("name_en", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
    )
    op.create_index(op.f("ix_permissions_slug"), "permissions", ["slug"], unique=True)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
    )
    op.create_index(op.f("ix_roles_slug"), "roles", ["slug"], unique=True)
    op.create_table(
        "semesters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_ar", sa.String(length=100), nullable=False),
        sa.Column("name_en", sa.String(length=100), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "registration_status",
            sa.Enum("CLOSED", "OPEN", name="registration_status"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_semesters")),
    )
    op.create_table(
        "users",
        sa.Column("national_id", sa.String(length=14), nullable=False),
        sa.Column("university_email", sa.String(), nullable=False),
        sa.Column("personal_email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("second_name", sa.String(length=50), nullable=False),
        sa.Column("third_name", sa.String(length=50), nullable=False),
        sa.Column("fourth_name", sa.String(length=50), nullable=False),
        sa.Column("family_name", sa.String(length=50), nullable=False),
        sa.Column("profile_picture_url", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_national_id"), "users", ["national_id"], unique=True)
    op.create_index(
        op.f("ix_users_university_email"), "users", ["university_email"], unique=True
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("table_name", sa.String(length=50), nullable=False),
        sa.Column("record_id", sa.String(length=50), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_table(
        "course_offerings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("semester_id", sa.Integer(), nullable=False),
        sa.Column("max_capacity", sa.Integer(), nullable=False),
        sa.Column("enrolled_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_course_offerings_course_id_courses"),
        ),
        sa.ForeignKeyConstraint(
            ["semester_id"],
            ["semesters.id"],
            name=op.f("fk_course_offerings_semester_id_semesters"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_offerings")),
    )
    op.create_table(
        "programs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_ar", sa.String(length=100), nullable=False),
        sa.Column("name_en", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column(
            "type", sa.Enum("GENERAL", "CREDIT", name="program_type"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_programs_department_id_departments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_programs")),
        sa.UniqueConstraint("code", name=op.f("uq_programs_code")),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "role_id", "permission_id", name=op.f("pk_role_permissions")
        ),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_user_roles_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_roles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    op.create_table(
        "concentrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_ar", sa.String(length=100), nullable=False),
        sa.Column("name_en", sa.String(length=100), nullable=False),
        sa.Column("min_level", sa.Integer(), nullable=False),
        sa.Column("min_credit_hours", sa.Integer(), nullable=True),
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_concentrations_program_id_programs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_concentrations")),
    )
    op.create_table(
        "program_bylaws",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.Column("bylaw_id", sa.Integer(), nullable=False),
        sa.Column("total_credit_hours", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bylaw_id"],
            ["faculty_bylaws.id"],
            name=op.f("fk_program_bylaws_bylaw_id_faculty_bylaws"),
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_program_bylaws_program_id_programs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_program_bylaws")),
    )
    op.create_table(
        "sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_offering_id", sa.Integer(), nullable=False),
        sa.Column("name_ar", sa.String(length=255), nullable=False),
        sa.Column("name_en", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum("LECTURE", "LAB", "TUTORIAL", name="section_type"),
            nullable=False,
        ),
        sa.Column(
            "day",
            sa.Enum(
                "SATURDAY",
                "SUNDAY",
                "MONDAY",
                "TUESDAY",
                "WEDNESDAY",
                "THURSDAY",
                "FRIDAY",
                name="day_of_week",
            ),
            nullable=False,
        ),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_offering_id"],
            ["course_offerings.id"],
            name=op.f("fk_sections_course_offering_id_course_offerings"),
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_sections_location_id_locations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sections")),
        sa.UniqueConstraint(
            "location_id",
            "day",
            "start_time",
            "end_time",
            name="uq_section_location_time",
        ),
    )
    op.create_table(
        "elective_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_ar", sa.String(length=100), nullable=False),
        sa.Column("name_en", sa.String(length=100), nullable=False),
        sa.Column("program_id", sa.Integer(), nullable=True),
        sa.Column("bylaw_id", sa.Integer(), nullable=False),
        sa.Column("required_credit_hours", sa.Integer(), nullable=False),
        sa.Column("min_courses", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bylaw_id"],
            ["program_bylaws.id"],
            name=op.f("fk_elective_groups_bylaw_id_program_bylaws"),
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_elective_groups_program_id_programs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_elective_groups")),
    )
    op.create_table(
        "students",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("student_code", sa.String(length=50), nullable=False),
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.Column("bylaw_id", sa.Integer(), nullable=False),
        sa.Column("concetration_id", sa.Integer(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("gpa", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("earned_credits", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "PROBATION", "SUSPENDED", "GRADUATED", name="student_status"
            ),
            nullable=False,
        ),
        sa.Column("gender", sa.Enum("MALE", "FEMALE", name="gender"), nullable=False),
        sa.Column(
            "religion",
            sa.Enum("MUSLIM", "CHRISTIAN", "OTHER", name="religion"),
            nullable=True,
        ),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("date_of_birth", sa.DATE(), nullable=True),
        sa.Column("place_of_birth", sa.String(length=255), nullable=True),
        sa.Column("national_id_issue_date", sa.DATE(), nullable=True),
        sa.Column("gov_address", sa.TEXT(), nullable=True),
        sa.Column("current_address", sa.TEXT(), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("governorate", sa.String(length=100), nullable=True),
        sa.Column("landline_phone", sa.String(length=20), nullable=True),
        sa.Column("guardian_name", sa.String(length=255), nullable=True),
        sa.Column("guardian_relation", sa.String(length=100), nullable=True),
        sa.Column("guardian_job", sa.String(length=255), nullable=True),
        sa.Column("guardian_phone", sa.String(length=20), nullable=True),
        sa.Column("guardian_national_id", sa.String(length=20), nullable=True),
        sa.Column(
            "military_status",
            sa.Enum(
                "EXEMPTED", "POSTPONED", "COMPLETED", "SERVING", name="military_status"
            ),
            nullable=True,
        ),
        sa.Column("military_number", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["bylaw_id"],
            ["program_bylaws.id"],
            name=op.f("fk_students_bylaw_id_program_bylaws"),
        ),
        sa.ForeignKeyConstraint(
            ["concetration_id"],
            ["concentrations.id"],
            name=op.f("fk_students_concetration_id_concentrations"),
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_students_program_id_programs"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_students_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_students")),
        sa.UniqueConstraint("student_code", name=op.f("uq_students_student_code")),
    )
    op.create_table(
        "bylaw_courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bylaw_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("concentration_id", sa.Integer(), nullable=True),
        sa.Column("semester_suggested", sa.Integer(), nullable=True),
        sa.Column("is_elective", sa.Boolean(), nullable=False),
        sa.Column("elective_group_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bylaw_id"],
            ["program_bylaws.id"],
            name=op.f("fk_bylaw_courses_bylaw_id_program_bylaws"),
        ),
        sa.ForeignKeyConstraint(
            ["concentration_id"],
            ["concentrations.id"],
            name=op.f("fk_bylaw_courses_concentration_id_concentrations"),
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_bylaw_courses_course_id_courses"),
        ),
        sa.ForeignKeyConstraint(
            ["elective_group_id"],
            ["elective_groups.id"],
            name=op.f("fk_bylaw_courses_elective_group_id_elective_groups"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bylaw_courses")),
    )
    op.create_table(
        "enrollments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("course_offering_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "WITHDRAWN", "FAILED", name="enrollment_status"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_offering_id"],
            ["course_offerings.id"],
            name=op.f("fk_enrollments_course_offering_id_course_offerings"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.user_id"],
            name=op.f("fk_enrollments_student_id_students"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrollments")),
    )
    op.create_table(
        "student_transfer_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("from_program_id", sa.Integer(), nullable=False),
        sa.Column("to_program_id", sa.Integer(), nullable=False),
        sa.Column("transfer_date", sa.DATE(), nullable=False),
        sa.Column("decree_number", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_program_id"],
            ["programs.id"],
            name=op.f("fk_student_transfer_history_from_program_id_programs"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.user_id"],
            name=op.f("fk_student_transfer_history_student_id_students"),
        ),
        sa.ForeignKeyConstraint(
            ["to_program_id"],
            ["programs.id"],
            name=op.f("fk_student_transfer_history_to_program_id_programs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_transfer_history")),
    )
    op.create_table(
        "course_prerequisites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("prerequisite_course_id", sa.Integer(), nullable=False),
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["bylaw_courses.id"],
            name=op.f("fk_course_prerequisites_course_id_bylaw_courses"),
        ),
        sa.ForeignKeyConstraint(
            ["prerequisite_course_id"],
            ["courses.id"],
            name=op.f("fk_course_prerequisites_prerequisite_course_id_courses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_prerequisites")),
    )
    op.create_table(
        "enrollment_sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("enrollment_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["enrollments.id"],
            name=op.f("fk_enrollment_sections_enrollment_id_enrollments"),
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("fk_enrollment_sections_section_id_sections"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrollment_sections")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("enrollment_sections")
    op.drop_table("course_prerequisites")
    op.drop_table("student_transfer_history")
    op.drop_table("enrollments")
    op.drop_table("bylaw_courses")
    op.drop_table("students")
    op.drop_table("elective_groups")
    op.drop_table("sections")
    op.drop_table("program_bylaws")
    op.drop_table("concentrations")
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_table("programs")
    op.drop_table("course_offerings")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_university_email"), table_name="users")
    op.drop_index(op.f("ix_users_national_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("semesters")
    op.drop_index(op.f("ix_roles_slug"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_slug"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_table("locations")
    op.drop_table("faculty_bylaws")
    op.drop_table("departments")
    op.drop_table("courses")
    # ### end Alembic commands ###
