"""Adding user name en fields

Revision ID: f28ac9ffbb99
Revises: 8895b2fb86fb
Create Date: 2026-02-22 18:14:52.694841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28ac9ffbb99'
down_revision: Union[str, Sequence[str], None] = '8895b2fb86fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name_ar', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('second_name_ar', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('third_name_ar', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('fourth_name_ar', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('family_name_ar', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('first_name_en', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('second_name_en', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('third_name_en', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('fourth_name_en', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('family_name_en', sa.String(length=50), nullable=False))
    op.drop_column('users', 'third_name')
    op.drop_column('users', 'second_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'family_name')
    op.drop_column('users', 'fourth_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fourth_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('family_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('second_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('third_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users', 'family_name_en')
    op.drop_column('users', 'fourth_name_en')
    op.drop_column('users', 'third_name_en')
    op.drop_column('users', 'second_name_en')
    op.drop_column('users', 'first_name_en')
    op.drop_column('users', 'family_name_ar')
    op.drop_column('users', 'fourth_name_ar')
    op.drop_column('users', 'third_name_ar')
    op.drop_column('users', 'second_name_ar')
    op.drop_column('users', 'first_name_ar')
    # ### end Alembic commands ###
